language: python
python: 2.7
install:
  - python bootstrap.py
  - bin/buildout annotate
  - bin/buildout -Nq
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
- bin/code-analysis
- bin/test
after_failure:
  - bin/buildout annotate
  - firefox -v
